In [333]:
import numpy as np

# A Single Neuron

Neuron with 3 inputs

In [334]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] + bias)
print(output)


2.3


Neuron with 4 inputs

In [335]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] +
          inputs[3]*weights[3] + bias)
print(output)

4.8


# A Layer of Neurons

3 Neurons with 4 inputs

In [336]:
inputs = [1, 2, 3, 2.5]

# Weights associated with each neuron
# input[i] * weights[i]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,

    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,

    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3

]
print(outputs)

[4.8, 1.21, 2.385]


Same code as above but with loops to handle dynamically-sized inputs and layers

In [337]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0

    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron’s output variable
        neuron_output += n_input*weight

    # Add bias
    neuron_output += neuron_bias
    
    # Put neuron’s result to the layer’s output list
    layer_outputs.append(neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


# Dot Product and Vector Addition

Mathematically

<img src="../public/images/dot_product.png" />

In code

In [338]:
# Where a & b are vectors (1D Arrays/Lists)
a = [1, 2, 3]
b = [2, 3, 4]
dot_product = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
print(dot_product)

# Dot products are a good way of computing the pre-activated values of a neuron
# 1. Adding all the products of corresponding input values and weight values (using the dot product)
# 2. Adding the result with the bias vector (using vector addition)

20


# A Single Neuron with NumPy

In [339]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

# (1.0 * 0.2) + (2.0 * 0.8) + ...
outputs = np.dot(weights, inputs) + bias

print(outputs)

4.8


# A Layer of Neurons with NumPy

In [340]:
# The weights of this network are now a matrix (2D Array)
# NumPy treats the dot product of a matrix and vector as a dot product of each vector in the matrix and the vector, outputing a list (vector) of dot products

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)


[4.8   1.21  2.385]


# A Batch of Data

In [341]:
# Its better for the neural network to take in multiple samples at once (batching)
# 1. Its faster
# 2. Helps the neural network build generalization, single samples can lead to the model making changes based only on a single sample

inputs = [[1, 2, 3, 2.5], [2, 5, -1, 2], [-1.5, 2.7, 3.3, -0.8]]

# Matrix Multiplication

In [342]:
# Matrix multiplication involves row vector and column vector dot products
# It creates a matrix of dot products of all the combinations of row and column vectors

# Row vector definition

np.array([[1, 2, 3]]) # List -> Matrix (vector into row vector)
# np.array([1, 2, 3]) creates a (3,) vector

a = [1, 2, 3]
np.array([a])

# Adds a dimension from (3,) to (1, 3)
a = [1, 2, 3]
np.expand_dims(np.array(a), axis=0)

# Col vector defintion
# The same as row vectors but transpose them (n x m => m x n)

a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

# np.dot(a, b)
a @ b # We get back a matrix (rather than a scalar in a dot product)


array([[20]])

# A Layer of Neurons & Batch of Data w/ NumPy

In [343]:
import numpy as np

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
